# -*- coding: utf-8 -*-
"""CodeAlpha_Data_Analytics_Tasks (1).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1E-B-vZN15SyYWVngduapdQxXR5CWyLEg

TASK 2: Exploratory Data Analysis (EDA)

Questions:
1. Who scored the highest and lowest marks?
2. What is the average marks of students?
3. Is there any difference between male and female performance?
4. Are there any missing values in the dataset?
5. Are there any unusual or extreme values?
"""

import pandas as pd

data = {
    "Name": ["A", "B", "C", "D"],
    "Marks": [85, 90, 78, 92],
    "Gender": ["M", "F", "M", "F"]
}

df = pd.DataFrame(data)

print("Dataset:\n", df)
print("\nData Info:\n")
print(df.info())
print("\nStatistical Summary:\n", df.describe())
print("\nMissing Values:\n", df.isnull().sum())

print("Highest Marks:", df["Marks"].max())
print("Lowest Marks:", df["Marks"].min())

print("\nAverage Marks:", df["Marks"].mean())

print("\nAverage Marks by Gender:\n", df.groupby("Gender")["Marks"].mean())

male_avg = df[df["Gender"] == "M"]["Marks"].mean()
female_avg = df[df["Gender"] == "F"]["Marks"].mean()

print("Male Average Marks:", male_avg)
print("Female Average Marks:", female_avg)

print("Missing Values:\n", df.isnull().sum())
print("Duplicate Rows:", df.duplicated().sum())

"""Analysis & Insights:

- Student D has the highest marks (92), while Student C has the lowest (78).
- The average marks of students is approximately 86.
- Female students have slightly higher average marks compared to male students.
- There are no missing values or duplicate records in the dataset.
- No extreme or abnormal values are observed.

Conclusion:

The dataset is clean and well-structured.
There is a slight trend showing female students performing better than male students.
Overall performance is consistent across students.

TASK 3: Data Visualization

Objective:
To transform raw data into visual formats like charts and graphs to understand patterns clearly and support decision-making.
"""

import matplotlib.pyplot as plt
import seaborn as sns

sns.barplot(x="Name", y="Marks", data=df)
plt.title("Marks of Students")
plt.xlabel("Student Name")
plt.ylabel("Marks")
plt.show()

sns.histplot(df["Marks"], bins=5)
plt.title("Distribution of Marks")
plt.xlabel("Marks")
plt.ylabel("Frequency")
plt.show()

sns.boxplot(x="Gender", y="Marks", data=df)
plt.title("Marks Distribution by Gender")
plt.xlabel("Gender")
plt.ylabel("Marks")
plt.show()

"""Visualization Insights:

- The bar chart shows that Student D has the highest marks and Student C has the lowest.
- The histogram shows marks are evenly distributed.
- The boxplot shows no extreme outliers.
- Female students have slightly higher marks than male students.

Data Story:

From the visualizations, we can understand that student performance is consistent.
There is a slight trend where female students perform better, and no abnormal patterns are observed.

TASK 4: Sentiment Analysis

Objective:
To analyze text data from sources like product reviews and classify it as positive, negative, or neutral using NLP techniques, and understand public opinion and trends.
"""

!pip install textblob

from textblob import TextBlob

reviews = [
    "This product is amazing and works perfectly",
    "Very bad experience, waste of money",
    "Average quality, not too good not too bad",
    "Excellent service and fast delivery",
    "Not satisfied with the product quality"
]

for review in reviews:
    analysis = TextBlob(review)

    if analysis.sentiment.polarity > 0:
        sentiment = "Positive"
    elif analysis.sentiment.polarity == 0:
        sentiment = "Neutral"
    else:
        sentiment = "Negative"

    print(review, "→", sentiment)

"""Sentiment Analysis Insights:

- Positive reviews indicate customer satisfaction and good product performance.
- Negative reviews highlight issues and dissatisfaction among customers.
- Neutral reviews represent average or mixed opinions.

Public Opinion & Trends:

- Most positive reviews suggest a good overall perception of the product.
- Negative feedback helps identify areas for improvement.
- Sentiment patterns help understand customer behavior and trends.

Applications:

- Helps businesses in marketing strategies.
- Supports product development and improvement.
- Provides social insights from customer opinions.
"""